CREATE TABLE IF NOT EXISTS `its_2018`.`studenti` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL COMMENT '	',
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL COMMENT '		',
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `skill` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(45) NULL DEFAULT NULL,
  `hobbies` VARCHAR(45) NULL DEFAULT NULL,
  `matricola` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8


